---
remote_theme : Modern Blog Version 2
title : "My IT note"
author : Yun Jeong LEE
url : "https://YunJeongL.github.io"
baseurl : ""
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
---

theme: jekyll-theme-merlot